### ISSUE TITLE
Ignore #1 - #10

### ISSUE THREAD

**Issue by jushar** [qaisjp/github-mantisbot#5]
Some commits use numbers from #1 to ~#5 to express that these commits belong to each other (as an addendum for example).

Since mantis issues between 1 and 10 don't exist anyway, I think we can ignore numbers between #1 and #10 in commit messages.

**Comment by qaisjp** [comment]
fixed in 9062db7bfbe11a134601f85d549a32022019e610

**Comment by jushar** [comment]
:+1:
